{
 "title": "Power Usage Chart",
 "time": { "from": "2024-04-09T10:43:38.916Z", "to": "2024-04-09T16:32:56.271Z" },
 "panels": [
  {
   "title": "Main kW Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"Main\")\n"
    }
   ]
  },
  {
   "title": "Predicted Values",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -24h)\n    |> filter(fn: (r) => r._measurement == \"power\" and (r._field == \"Dryer\" or r._field == \"HVAC\" or r._field == \"Recs\" or r._field == \"Washer\" or r._field == \"Other\" or r._field == \"WaterHeater\" or r._field == \"Lights\"))\n"
    }
   ]
  },
  {
   "title": "Average Total Power Load",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -12h)\n    |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"Main\")\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost Breakdown",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -6h)\n    |> filter(fn: (r) => r._measurement == \"cost\" and (r._field == \"Dryer_Cost\" or r._field == \"HVAC_Cost\" or r._field == \"Recs_Cost\" or r._field == \"Washer_Cost\" or r._field == \"Other_Cost\" or r._field == \"WaterHeater_Cost\" or r._field == \"Lights_Cost\"))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Power Cost 24Hrs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 13, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -24h)\n    |> filter(fn: (r) => r._measurement == \"cost\" and (r._field == \"Dryer_Cost\" or r._field == \"HVAC_Cost\" or r._field == \"Recs_Cost\" or r._field == \"Washer_Cost\" or r._field == \"Other_Cost\" or r._field == \"WaterHeater_Cost\" or r._field == \"Lights_Cost\"))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cost Breakdown",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -24h)\n    |> filter(fn: (r) => r._measurement == \"cost\" and (r._field == \"Dryer_Cost\" or r._field == \"HVAC_Cost\" or r._field == \"Recs_Cost\" or r._field == \"Washer_Cost\" or r._field == \"Other_Cost\" or r._field == \"WaterHeater_Cost\" or r._field == \"Lights_Cost\"))\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HVAC Predicted Values",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -6h)\n    |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"HVAC\")\n"
    }
   ]
  },
  { "title": "TEST AREA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Costs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"Cost\")"
    }
   ]
  },
  {
   "title": "Fixed? Gauges",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -30d)\n"
    }
   ]
  },
  {
   "title": "NOT FIXED Main Chart",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -30d)\n    |> filter(fn: (r) => r._measurement == \"power\" and r._field == \"Main\")   "
    }
   ]
  },
  {
   "title": "Predicted Values",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket:\"predicted_loads\")\n    |> range(start: -6h)\n    |> filter(fn: (r) => r._measurement == \"power\" and (r._field == \"Dryer\" or r._field == \"HVAC\" or r._field == \"Recs\" or r._field == \"Washer\" or r._field == \"Other\" or r._field == \"WaterHeater\" or r._field == \"Lights\"))\n"
    }
   ]
  }
 ]
}